### ISSUE TITLE
Super cool idea!

### ISSUE THREAD

**Issue by RandyGaul** [NoelFB/c89_nolib#1]
No clue what your personal restrictions are but I just found this the other day, could be useful if you wanna make a sin/cos function https://github.com/rutgers-apl/The-RLIBM-Project

**Comment by NoelFB** [comment]
Ohh cool, this looks really interesting, thank you! Yeah, I'm not really sure where I'm going with this... probably a very tiny platformer, but having sin/cos would be really nice.
